import Head from "next/head";
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen bg-stone-700 text-stone-200 p-4'>
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default MyApp;
